config/routes.rb
Rails.application.routes.draw do
  get 'sules/show'
  resources :sules
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users do  
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create]
  
  root to: 'sules#teamindex'
  get 'sule/itiran',          to: 'sules#itiran'
  get 'sules/index/:teamatr', to: 'sules#index', as: :sule_index_path
  get 'sules/show/:id' ,      to: 'sules#show', as: :sule_show_path
  post 'sules/index',         to: 'sules#create', as: :sule_create_path
  post 'sules/show',          to: 'commes#create', as: :comme_create_path
  get  'sules/new',           to: 'sules#new'
  get 'sules/search',         to: 'sules#search'
  get   'users/show/:id',     to: 'users#show', as: :users_show_path
  delete 'sules/show/:id',    to: 'commes#destroy', as: :commes_destroy
  patch 'users/show/:id',      to: 'users#update', as: :team_update
  
end

app/models/sule.rb
class Sule < ApplicationRecord
    validates :name, length:{maximum: 20}, presence: true
    #validates :content, length:{maximum: 40}
    validates :teamatr, presence: true, format:{with: /[Giants,Tigers,BayStars,Dragons,Swallows,Carp]/}
    validates :content, length:{maximum: 225}, presence: true
    has_many :commes
    has_many :replies
    has_many :browsing_histories
    mount_uploader :image, ImageUploader
    validate :image_size
    belongs_to :user

    def self.search(search)
        return Sule.all unless search
        Sule.where(["name LIKE? OR content LIKE?", "%#{search}%", "%#{search}%"])
    end
    
    private
    def image_size
      if image.size > 5.megabytes
        errors.add(:picture, "5MB以下にしてください")
      end
    end 
end

app/controllers/sules_controller.rb
class SulesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  
  def teamindex
    @sules=Sule.all.order(ikioi: "DESC").limit(8)
    @new_sules=Sule.all.order(created_at: "DESC").limit(8)
    if user_signed_in?
      @browsing_histories=current_user.browsing_histories.all.order(created_at: "DESC")
      @followings=current_user.feed.page(params[:page]).per(8)
      @fav_sules=Sule.where(teamatr: current_user.fav_team).order(ikioi: "DESC").limit(8)
    end
    @chart=Sule.group(:teamatr).count
    @user=User.all
  end
  
  
  def index
    @sules=Sule.where(teamatr: params[:teamatr]).order(:id).page(params[:page]).per(20)
    @newsule=Sule.new(teamatr: params[:teamatr])
  end
  
  def itiran
    @sules=Sule.search(params[:search]).page(params[:page])
  end

  
  def show
    @sule=Sule.find(params[:id])
    @sule.ikioi=(@sule.commes.count+@sule.replies.count).to_f*86400/(Time.now.to_f-@sule.created_at.to_f)
    @sule.save
    if current_user
      new_bh=@sule.browsing_histories.new
      new_bh.user_id=current_user.id
    
      if current_user.browsing_histories.exists?(sule_id: "#{params[:id]}")
        old_bh=current_user.browsing_histories.find_by(sule_id: "#{params[:id]}")
        old_bh.destroy
      end
      new_bh.save
    
      bh_limit=6
      history=current_user.browsing_histories.all
      if history.count > bh_limit
        history[0].destroy
      end
    end
    
    @commes=Comme.where(sule_id: params[:id]).page(params[:page]).per(20).limit(1000)
    @newcomme=Comme.new(sule_id: params[:id])
    @newreply=Reply.new(sule_id: params[:id])
  
  end
  
  def create
    @sule=Sule.new(sule_params)
    @sule.user_id=current_user.id
    if @sule.save
      redirect_to sule_show_path_url(id: @sule.id), notice: '成功しました'
    else
      redirect_back(fallback_location: root_path)
    end
  end
  

  

  
  private
    def sule_params
       params.require(:sule).permit(:name,:teamatr, :content, :image, :ikioi)
    end      
  

end

app/helpers/sules_helper.rb
module SulesHelper
end

app/views/sules/_newsule.html.slim
=form_for @newsule, url:sule_create_path_url do|f|
    =f.label :name, "スレッド名"
    br
    =f.text_field :name, class:"form-control"
    br
    =f.label :content, "スレッドの内容"
    br
    =f.text_area :content, class:"form-control"
    br
    =f.label "画像をアップロード"
    br
    =f.file_field :image
    br
    =f.hidden_field :teamatr
    =f.button class:"btn btn-block btn-info"

app/views/sules/_sule.html.slim
=link_to sule_show_path_url(sule), class: "list-group-item"
  .sule_name
    =sule.name
  br
  .sule_content
    =sule.content
  br
  .text-right
    -if Time.now.to_i-sule.created_at.to_i<86400
      span class="badge badge-info"
        |new
    br
    |勢い：
    =sule.ikioi
    br
    =sule.created_at.to_s(:datetime_jp)

app/views/sules/_team.html.slim
ul class="list-group" style="max-width: 400px;"
     =link_to "GIANTS", sule_index_path_url(teamatr: "Giants"), class:"list-group-item"
     =link_to "BayStars", sule_index_path_url(teamatr: "BayStars") , class:"list-group-item"
     =link_to "Tigers", sule_index_path_url(teamatr: "Tigers"), class:"list-group-item"
     =link_to "Carp", sule_index_path_url(teamatr: "Carp") , class:"list-group-item"
     =link_to "Dragons", sule_index_path_url(teamatr: "Dragons"), class:"list-group-item"
     =link_to "Swallows", sule_index_path_url(teamatr: "Swallows"), class:"list-group-item"

app/views/sules/index.html.slim
nav aria-label="パンくずリスト"
  ol class="breadcrumb"
    li class="breadcrumb-item"
      =link_to root_path
       |ホーム
      
    li class="breadcrumb-item active" aria-current="page"
      = "#{params[:teamatr]}のスレッド一覧"
h1トピック一覧
.row
  .col-sm-8
    ul class="list-group" style="max-width: 700px;"
      =render @sules
      = paginate @sules
  .col-sm-4
    -if signed_in?
      =render 'newsule'
    -else
      button class="btn btn-lg btn-info btn-block" data-toggle="modal" data-target="#signUpModal"
        |新規登録してスレッドを作成する    

app/views/sules/itiran.html.slim
h2 検索
=form_tag(sule_itiran_path, :method =>'get')do
    =text_field_tag :search
    = submit_tag 'Search', class:"btn btn-info"

h2　スレッド一覧
-if @sules.empty?
    |検索結果に一致するスレッドはありません
-else
    .list-group
        =render @sules
        =paginate @sules

app/views/sules/new.js.erb
$("#mo-modal").html("<%= escape_javascript(render('sules/form')) %>");
$("#mo-modal").modal("show");

app/views/sules/new_sules.html.slim
/=link_to sule_show_path_url(new_sule) class:"list-group-item"
 =new_sule.name
 br
 =new_sule.content
 

app/views/sules/show.html.slim
<nav aria-label="パンくずリスト">
  ol class="breadcrumb mb-1"
    li class="breadcrumb-item"
      =link_to root_path
        |ホーム
    li class="breadcrumb-item"
      =link_to sule_index_path_url(teamatr: @sule.teamatr)
        ="#{@sule[:teamatr]}のスレッド一覧"
    li class="breadcrumb-item active" aria-current="page"
      |データ
h1 =@sule.name
div class="row"
  div class="col-sm-8"
    ul class="list-group" style="max-width: 800px"
      li class="list-group-item"
        .commename
          =link_to "#{@sule.user.username}", users_show_path_url(@sule.user)
        .content
          = @sule.content
          br
          -if @sule.image?
            =image_tag @sule.image.url
        p class="text-right"
              =@sule.created_at.to_s(:datetime_jp)
      - if @sule.commes.any?
        - @commes.each_with_index do|comme , x|
          li class="list-group-item"
            div class="commename"
              =x+1
              span style="margin-right: 16px;"
              =link_to users_show_path_url(comme.user)
                =comme.user.username
            p
            div class="comment"
              =comme.comment
              br
              -if comme.image?
                =image_tag comme.image.url
            div class="text-right"
              -if user_signed_in?
                button type="button"  class="btn btn-success" data-toggle="modal" data-target="#replymodal#{comme.id}" 
                 |reply
              -if @sule.user==current_user
                =link_to "削除", commes_destroy_path(comme), class:"btn btn-danger", method: :delete
            p
            p class="text-right"
              =comme.created_at.to_s(:datetime_jp)
              
            p
            div class="modal fade" id="replymodal#{comme.id}" tabinex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true"
              .modal-dialog role="document"
                .modal-content
                  .modal-header
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true" >&times;</button>
                     
            
        
                  = form_for(@newreply, url: replies_path(comme_id: comme.id), remote: true) do |f|
                    .modal-body
                        =f.label :reply   
                        br
                        =f.text_area :reply, class:"form-control"
                        br 
                        =f.label "画像をアップロード"
                        br
                        =f.file_field :image
                    .modal-fotter
                      .text-right
                        button type="button" class="btn btn-defauld" data-dismiss="modal" キャンセル
                        =f.button '送信', class: "btn btn-primary"
                        =f.hidden_field :user_id
                        =f.hidden_field :sule_id
                        =f.hidden_field :comme_id, value: comme.id
          
          -if comme.replies.any?
            -comme.replies.each do|reply|
              .reply
                li class="list-group-item list-group-item-primary"
                  |➥
                  =link_to users_show_path_url(reply.user)
                    =reply.user.username
                  p
                  .reply-content
                  =reply.reply
                  p
                  -if reply.image?
                    =image_tag reply.image.url
                  p class="text-right"
                    -if user_signed_in?
                      button type="button"  class="btn btn-success" data-toggle="modal" data-target="#replymodal#{comme.id}" 
                        |reply  
                    br
                    =reply.created_at.to_s(:datetime_jp)

                  
                
        = paginate @commes   
                
                
                
            
  div class="col-sm-4"

   
    .modal fade #sule-modal tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true"
    -if user_signed_in?  
      button class="btn btn-info btn-lg btn-block" data-toggle="modal" data-target="#createComme" コメントする
   
      div class="modal fade" id="createComme" tabinex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true"
        div class="modal-dialog"
          div class="modal-content"
            div class="modal-header"
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true" >&times;</button>
              
            
            =form_for(@newcomme,  url: comme_create_path_url, remote: true) do |f|
              .modal-body
                =f.label :comment, "コメント" 
                =f.text_area :comment, class: "form-control"
                br
                span  class="image"
                  =f.file_field :image
              
              .modal-footer
                button type="button" class="btn btn-defauld" data-dismiss="modal" キャンセル
                =f.button 'コメントを送信', class: "btn btn-primary", data:{disable_with: "送信中..."}
                =f.hidden_field :sule_id
                =f.hidden_field :user_id
    -else
      button class="btn btn-lg btn-info btn-block" data-toggle="modal" data-target="#signUpModal"
        |新規登録してコメントする
              



   

app/views/sules/teamindex.html.slim
nav aria-label="パンくずリスト"
  ol class="breadcrumb"
    li class="breadcrumb-item active" aria-current="page"
      |ホーム

.jumbotron
  .container
    h1 セリーグファンの交流掲示板です。
    -unless signed_in? 
      .lead このサイトはNPBのセリーグファンのためのwebアプリケーションです。ログインしなくても閲覧はできますが、新規登録しログインするとスレッドの作成やコメントの投稿ができるようになります。
    -unless signed_in?
      button class="btn btn-lg btn-info btn-block" data-toggle="modal" data-target="#signUpModal"
          |新規登録してコメントする
-if user_signed_in?
  .row
      .col-sm-5
        h2 新着記事
        .list-group style="max-width: 470px"
          =render @new_sules
     
        

      .col-sm-5
        h2 勢いが高い記事
        .list-group style="max-width: 470px"
          =render @sules
      .col-sm-2
        h2 チーム一覧
        =render 'team'
  .row   
      .col-sm-4
        
        h2 お気に入りのチームの記事
        -if current_user.fav_team==nil?
          br
          br
          =link_to "お気に入りのチームを登録する", users_show_path_url(current_user), class: "btn btn-info"
        .list-group style="max-width: 470px"
          =render @fav_sules
      .col-sm-4
        h2 フォロー中の人のコメント
        .list-group style="max-width: 470px"
         -if @followings.any?
          -@followings.each do|f|
            .list-group-item 
              =link_to "#{f.user.username}", users_show_path_url(f.user)
              br
              -if f.reply_id.nil?
                =f.comme.comment
                .text-right
                  |スレッド名:
                  =f.comme.sule.name
              -else
                =f.reply.reply
                .text-right
                  |スレッド名:
                  =f.reply.sule.name
          =paginate @followings
         -else 
            br
            h4 フォローしている人のコメントはありません
            br
            
      .col-sm-4
        h2 最近見た記事
        .list-group style="max-width: 470px"
          -if @browsing_histories.any?
            =render @browsing_histories
          -else
            br
            h4 最近見た記事はありません
            br

-else
  .row
      .col-sm-5
          h2 勢いの高いスレッド
          .list-group style="max-width: 470px"
            =render @sules
      .col-sm-5
          h2 新着
          .list-group style="max-width: 470px"
            =render @new_sules
            
      .col-sm-2 
        h2 チーム一覧
        =render 'team' 
.row
  .col-sm-6
    h4 スレッドの内訳
    =pie_chart @chart.sort ,colors: ["#61c2fa", "#f06969","#7097e6","#e6966c","#92e670","#fe3"]
  .col-sm-6
    h4 ファン数
    =bar_chart @user.group(:fav_team).count, colors:["#4eccbb"]        
        
        
    
      