config/routes.rb
Rails.application.routes.draw do
  get 'sules/show'
  resources :sules
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users do  
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create]
  
  root to: 'sules#teamindex'
  get 'sule/itiran',          to: 'sules#itiran'
  get 'sules/index/:teamatr', to: 'sules#index', as: :sule_index_path
  get 'sules/show/:id' ,      to: 'sules#show', as: :sule_show_path
  post 'sules/index',         to: 'sules#create', as: :sule_create_path
  post 'sules/show',          to: 'commes#create', as: :comme_create_path
  get  'sules/new',           to: 'sules#new'
  get 'sules/search',         to: 'sules#search'
  get   'users/show/:id',     to: 'users#show', as: :users_show_path
  delete 'sules/show/:id',    to: 'commes#destroy', as: :commes_destroy
  patch 'users/show/:id',      to: 'users#update', as: :team_update
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length:{maximum: 20}, uniqueness: true
  validates :fav_team, presence: false
  has_many :commes, dependent: :destroy
  has_many :sules
  has_many :replies, dependent: :destroy
  has_many :browsing_histories
  has_many :comment_histories
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "follow_id",
                                  dependent:  :destroy
  has_many :following, through: :active_relationships, source: :follow
  has_many :followers, through: :passive_relationships, source: :follower
  
  def follo(other_user)
    following<< other_user
  end
  
  def unfollow(other_user)
    active_relationships.find_by(follow_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def feed
    CommentHistory.where("user_id IN (?) ", following_ids)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
     super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      a=resource.errors.full_messages.to_a
      redirect_to params[:user][:url], notice: "#{a[0]} #{a[1]} #{a[2]}"
    end
  end
  
  def failed 
    flash[:alert]="error"
    redirect_to params[:user][:url]
  end

  # GET /resource/edit
  def edit
     super
  end

  # PUT /resource
  def update
     super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
     auth_options = { scope: resource_name, recall: "#{controller_path}#failed" }
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end
  
  def failed
    flash[:alert] = "メールアドレスまたはパスワードが違います。"
    
    redirect_back(fallback_location: root_path)
  end
  

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only:[:update]
    def show
        @user=User.find(params[:id])
        @comment_histories=@user.comment_histories.order(created_at: "DESC")
        @followings=@user.following.all
        @sules=Sule.where(user_id: @user.id).order(created_at: "DESC").limit(5)
        @chart=@user.commes.group("date(created_at)").count
        @today_comment=@user.commes.where("created_at LIKE?", "%#{Time.zone.today}%").count+ @user.replies.where("created_at LIKE?", "%#{Time.zone.today}%").count
        @yesterday_comment=@user.commes.where("created_at LIKE?", "%#{Time.zone.yesterday}%").count+ @user.replies.where("created_at LIKE?", "%#{Time.zone.yesterday}%").count
    end
    
    def following
        @title ="フォロー中の人"
        @user=User.find(params[:id])
        @users=@user.following.page(params[:page]).per(20)
        render 'show_follow'
    end
    
    def followers
        @title ="フォロワー"
        @user=User.find(params[:id])
        @users=@user.followers.page(params[:page]).per(20)
        render 'show_follow'
    end
    
    def update
        @user=User.find_by(id: params[:id])
        @user.update(user_params)
           
            redirect_to users_show_path_url(@user)
    end
    
    private
    def user_params
        params.require(:user).permit(:fav_team)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.slim
=form_for(current_user.active_relationships.build, remote: true) do |f|
                =hidden_field_tag :followed_id, @user.id
                =f.submit "フォローする", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
        -if current_user.following?(@user)
            =render'unfollow'
        -else
            =render 'follow'
            

app/views/users/_unfollow.html.slim
=form_for(current_user.active_relationships.find_by(follow_id: @user.id), html: {method: :delete}, remote: true) do |f|
                =f.submit "フォロー解除", class: "btn"
                

app/views/users/show.html.slim
nav aria-label="パンくずリスト"
  ol class="breadcrumb"
    li class="breadcrumb-item"
      =link_to root_path
       |ホーム
    
    li class="breadcrumb-item active" aria-current="page"
        -if @user==current_user 
            |マイページ
        -else
            |ユーザーページ
.row
    .col-sm-5
        h1 =@user.username

        |総コメント数:  
        =@user.commes.count
        br
        |今日のコメント数:
        =@today_comment
        br
        =@yesterday_comment
        ="(前日比#{@today_comment-@yesterday_comment})"
        br
        =link_to "フォロー数:",  following_user_url(@user), :style=>"color:black"
        =@user.following.count
        br
        =link_to "フォロワー数", followers_user_url(@user), :style=>"color:black"
        =@user.followers.count
        br 
        |お気に入りのチーム:
        =@user.fav_team
        -if signed_in?
            -unless current_user.id==@user.id
                =render 'follow_form'  
            -else
                =form_for @user, url: team_update_url do |f|
                    =f.select :fav_team,[ ["BayStars","BayStars" ],["Carp", "Carp"],["Dragons", "Dragons"],["Giants", "Giants"],["Tigers", "Tigers"],["Swallows","Swallows"]]
                    =f.button "変更", class:"btn btn-info"
        br 
        
        =line_chart @chart
    
    .col-sm-7
        h2 作成したスレッド
        -if @sules.any?
            =render @sules
        -else
            br
            h4 作成したスレッドはありません
            br
    
        h2 最近したコメント
        -if @comment_histories.any?
            .list-group style="max-width:400px"
            -if @comment_histories.any?
             -@comment_histories.each do|c|
                -if c.reply_id.nil?
                    =link_to sule_show_path_url(c.comme.sule), class: "list-group-item"
                        =c.comme.comment
                        br
                        .text-right
                            |スレッド名:
                            =c.comme.sule.name
                            br        
                            =c.created_at.to_s(:datetime_jp)
                            br
                -else
                    =link_to sule_show_path_url(c.reply.comme.sule), class: "list-group-item"
                        =c.reply.reply
                        br
                        .text-right
                            |スレッド名: 
                            =c.reply.comme.sule.name
                            br
             
                            =c.created_at.to_s(:datetime_jp)
                 
        -else
            br
            h4 コメントはありません
            br
    
  
 

app/views/users/show_follow.html.slim
.row
    .col-xs-4
            h1
                =link_to  @user.username, users_show_path_url(@user), :style=>"color:black"
            br 
            |コメント数:
            =@user.commes.count
    .col-xs-8
            h3  = @title
            -if @users.any?
                - @users.each do |x|
                    =link_to x.username, users_show_path_url(x), class:"badge badge-light"
                    |　
                = paginate @users
             
            -else 
                ="#{@title}は存在しません"
            
                
                    
                