config/routes.rb
Rails.application.routes.draw do
  get 'sules/show'
  resources :sules
  devise_for :users, controllers:{
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }
  resources :users do  
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :replies, only: [:create]
  
  root to: 'sules#teamindex'
  get 'sule/itiran',          to: 'sules#itiran'
  get 'sules/index/:teamatr', to: 'sules#index', as: :sule_index_path
  get 'sules/show/:id' ,      to: 'sules#show', as: :sule_show_path
  post 'sules/index',         to: 'sules#create', as: :sule_create_path
  post 'sules/show',          to: 'commes#create', as: :comme_create_path
  get  'sules/new',           to: 'sules#new'
  get 'sules/search',         to: 'sules#search'
  get   'users/show/:id',     to: 'users#show', as: :users_show_path
  delete 'sules/show/:id',    to: 'commes#destroy', as: :commes_destroy
  patch 'users/show/:id',      to: 'users#update', as: :team_update
  
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | EventApp
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body
    
    header.navbar.navbar-default[role="navigation"]
      .container
        .navbar-header
          = link_to 'baseball-ce!', root_path, class: 'navbar-brand', id: "logo"
        nav
          ul class="nav navbar-nav navbar-right"
            li =link_to "全スレッド一覧", sule_itiran_url
            - if user_signed_in?
              li = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item nav-link active"
              li = link_to "マイページ", users_show_path_url(current_user)
            - else
              li 
                a class="nav-link" type="button" data-toggle="modal" data-target="#signUpModal"
                 |新規登録
              li 
                a class="nav-link" type="button" data-toggle="modal" data-target="#loginmodal"
                  |ログイン
            li =link_to "戻る", :back
    
    .container      
      p.notice
        = notice
      p.alert
        = alert
    .container
      = yield
    -unless user_signed_in?
      =render "devise/registrations/new" 
      =render "devise/sessions/new"
    script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"
  
    footer
      br
      p baseball-ce!